language: node_js

node_js:
  - 'node'

sudo: false

install:
  - npm install

script:
  - npm test
  - npm run build

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
