language: node_js

node_js:
  - 'node'

sudo: false

services:
  - postgresql

install:
  - npm install

script:
  - npm run build
  - npm test

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
