version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports: 
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    volumes:
      - /var/lib/postgresql/data:/data/postgres
    environment:
      # Defaults values if .env file is not found or variables missing
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-horsin-around}
    networks:
      - postgres
 
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports: 
      - ${PGADMIN_HOST_PORT:-8080}:${PGADMIN_CONTAINER_PORT:-80}
    environment:
      # Defaults values if .env file is not found or variables missing
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge