version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      # Defaults values if .env file is not found or variables missing
      - POSTGRES_USER: ${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      - POSTGRES_DB: ${POSTGRES_DB:-horsinaround}
    networks:
      - postgres
 
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      # Defaults values if .env file is not found or variables missing
      - PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge