version: "3"
services:
  # MySQL Database
  db:
    container_name: mysql
    image: mysql:5.7.21
    volumes:
      - "./db_data:/var/lib/mysql"
    ports: 
      - ${MYSQL_PORT:-3306}:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DB:-horsin-around}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    networks:
      - mysql

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_HOST_PORT:-8080}:${PHPMYADMIN_CONTAINER_PORT:-80}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - mysql

networks:
  mysql:
    driver: bridge